/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorBalok;

import java.awt.event.ItemEvent;
import java.lang.*;
import javax.swing.JOptionPane;

/**
 *
 * @author vena
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jButtonHitung = new javax.swing.JButton();
        jLabelP = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        jLabelL = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jRadioLP = new javax.swing.JRadioButton();
        jRadioV = new javax.swing.JRadioButton();
        jLabelH = new javax.swing.JLabel();
        jTextT = new javax.swing.JTextField();
        jTextH = new javax.swing.JTextField();
        jTextL = new javax.swing.JTextField();
        jTextP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHitung);
        jButtonHitung.setBounds(192, 251, 72, 23);

        jLabelP.setText("Panjang");
        getContentPane().add(jLabelP);
        jLabelP.setBounds(90, 55, 69, 16);

        jLabelT.setText("Tinggi");
        getContentPane().add(jLabelT);
        jLabelT.setBounds(90, 129, 69, 16);

        jLabelL.setText("Lebar");
        getContentPane().add(jLabelL);
        jLabelL.setBounds(90, 92, 69, 16);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("KALKULATOR BALOK");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(139, 16, 171, 20);

        buttonGroup.add(jRadioLP);
        jRadioLP.setText("Luas Permukaan");
        jRadioLP.setToolTipText("");
        jRadioLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLPActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioLP);
        jRadioLP.setBounds(90, 166, 136, 21);

        buttonGroup.add(jRadioV);
        jRadioV.setText("Volume");
        jRadioV.setToolTipText("");
        jRadioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioVActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioV);
        jRadioV.setBounds(266, 166, 136, 21);

        jLabelH.setText("Hasil");
        getContentPane().add(jLabelH);
        jLabelH.setBounds(90, 205, 69, 16);

        jTextT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTActionPerformed(evt);
            }
        });
        getContentPane().add(jTextT);
        jTextT.setBounds(295, 126, 71, 22);

        jTextH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextH);
        jTextH.setBounds(287, 199, 71, 22);

        jTextL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLActionPerformed(evt);
            }
        });
        getContentPane().add(jTextL);
        jTextL.setBounds(295, 92, 71, 22);

        jTextP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPActionPerformed(evt);
            }
        });
        getContentPane().add(jTextP);
        jTextP.setBounds(295, 52, 71, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        try {
            String pString = jTextP.getText();
            String lString = jTextL.getText();
            String tString = jTextT.getText();
            
            Double panjang = Double.parseDouble(pString);
            Double lebar = Double.parseDouble(lString);
            Double tinggi = Double.parseDouble(tString);
            
            Double luasP = 2*panjang*lebar+2*panjang*tinggi+2*lebar*tinggi;
            Double volume = panjang*lebar*tinggi;
            
            if(jRadioLP.isSelected()){
                jTextH.setText(luasP + " cm^2");
            }
            else if(jRadioV.isSelected()){
                jTextH.setText(volume + " cm^3");
            }
            else{
                jTextH.setText("0");
            }
            
            
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Input tidak sesuai!");
        }
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jTextTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTActionPerformed

    private void jTextHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHActionPerformed

    private void jTextLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLActionPerformed

    private void jTextPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPActionPerformed

    private void jRadioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioVActionPerformed

    private void jRadioLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioLPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JLabel jLabelH;
    private javax.swing.JLabel jLabelL;
    private javax.swing.JLabel jLabelP;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JRadioButton jRadioLP;
    private javax.swing.JRadioButton jRadioV;
    private javax.swing.JTextField jTextH;
    private javax.swing.JTextField jTextL;
    private javax.swing.JTextField jTextP;
    private javax.swing.JTextField jTextT;
    // End of variables declaration//GEN-END:variables
}
